import { type Product } from '@/lib/store'

const SILVER_JEWELRY_IMAGES = [
  'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1515562141589-67f0d569b6f5?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop',
]

const TAGLINE = 'joyería de autor, plata 925, Zacatecas México'

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-1',
    name: 'Anillo Luna Celestial',
    description: `Anillo artesanal en plata 925 con motivo de luna creciente y acento de circonia cúbica — ${TAGLINE}`,
    price: 1899.99,
    category: 'anillos',
    sku: 'RG-001',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[0]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    name: 'Collar Cadena Susurro',
    description: `Collar de cadena delicada en plata 925 con dije minimalista, perfecto para capas — ${TAGLINE}`,
    price: 2499.99,
    category: 'collares',
    sku: 'NK-002',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[1]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    name: 'Pulsera Cuff Etérea',
    description: `Pulsera tipo cuff de punta abierta en plata 925 pulida con diseño orgánico fluido — ${TAGLINE}`,
    price: 2899.99,
    category: 'pulseras',
    sku: 'BR-003',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[2]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    name: 'Aretes Gota de Cristal',
    description: `Aretes elegantes tipo gota en montura de plata 925 con cristales transparentes — ${TAGLINE}`,
    price: 1399.99,
    category: 'aretes',
    sku: 'ER-004',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[3]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    name: 'Anillo Infinito',
    description: `Diseño simbólico de infinito en plata oxidada con detalles pulidos — ${TAGLINE}`,
    price: 1599.99,
    category: 'anillos',
    sku: 'RG-005',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[4]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    name: 'Gargantilla Riviera',
    description: `Gargantilla statement en plata 925 con elementos geométricos entrelazados — ${TAGLINE}`,
    price: 3699.99,
    category: 'collares',
    sku: 'NK-006',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[5]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-7',
    name: 'Set Pulseras Onda',
    description: `Set de 3 pulseras apilables con textura inspirada en las olas en plata cepillada — ${TAGLINE}`,
    price: 2299.99,
    category: 'pulseras',
    sku: 'BR-007',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[6]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-8',
    name: 'Aretes Perla Clásica',
    description: `Perlas clásicas sobre postes de plata 925 con seguros mariposa — ${TAGLINE}`,
    price: 1199.99,
    category: 'aretes',
    sku: 'ER-008',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[7]],
    createdAt: new Date().toISOString(),
  },
]

export const DEMO_HASHTAGS = [
  { id: 'ht-1', name: 'Plata Esencial', hashtags: ['#Plata925', '#JoyeriaDePlata', '#SterlingSilver', '#Plata925Mexico', '#PlataPura', '#DiseñoPlata', '#ArtePlata', '#JoyeriaAdicta'], category: 'general', usageCount: 24 },
  { id: 'ht-2', name: 'Vibras de Lujo', hashtags: ['#JoyeriaDeLujo', '#Finajoyeria', '#EstiloElegante', '#BellezaAtemporal', '#AmantesJoyeria', '#VidaDeLujo', '#JoyeriaChic', '#EstiloClasico'], category: 'lujo', usageCount: 18 },
  { id: 'ht-3', name: 'Colección Anillos', hashtags: ['#AnilloPlata', '#Anillos925', '#ColeccionAnillos', '#AnilloPromesa', '#AnilloStatement', '#AnilloMinimal', '#StackAnillos', '#EstiloAnillos'], category: 'anillos', usageCount: 31 },
  { id: 'ht-4', name: 'Tendencias', hashtags: ['#TendenciasJoyeria', '#Joyeria2025', '#TendenciaActual', '#MustHave', '#InspiracionEstilo', '#OOTD', '#JoyeriaGram', '#InstaJoyeria'], category: 'tendencias', usageCount: 15 },
]

export const DEMO_ANALYTICS = [
  { date: '2026-05-01', likes: 245, comments: 32, shares: 18, reach: 4200, platform: 'instagram' },
  { date: '2026-05-02', likes: 312, comments: 45, shares: 22, reach: 5100, platform: 'instagram' },
  { date: '2026-05-03', likes: 189, comments: 21, shares: 14, reach: 3200, platform: 'facebook' },
  { date: '2026-05-04', likes: 421, comments: 56, shares: 35, reach: 6800, platform: 'instagram' },
  { date: '2026-05-05', likes: 278, comments: 38, shares: 19, reach: 4500, platform: 'facebook' },
  { date: '2026-05-06', likes: 356, comments: 42, shares: 28, reach: 5600, platform: 'instagram' },
  { date: '2026-05-07', likes: 198, comments: 25, shares: 16, reach: 3400, platform: 'facebook' },
  { date: '2026-05-08', likes: 489, comments: 67, shares: 42, reach: 7200, platform: 'instagram' },
  { date: '2026-05-09', likes: 334, comments: 48, shares: 31, reach: 5400, platform: 'facebook' },
  { date: '2026-05-10', likes: 412, comments: 55, shares: 38, reach: 6500, platform: 'instagram' },
  { date: '2026-05-11', likes: 267, comments: 34, shares: 21, reach: 4300, platform: 'facebook' },
  { date: '2026-05-12', likes: 523, comments: 72, shares: 45, reach: 7800, platform: 'instagram' },
  { date: '2026-05-13', likes: 345, comments: 41, shares: 27, reach: 5100, platform: 'facebook' },
  { date: '2026-05-14', likes: 478, comments: 63, shares: 39, reach: 7000, platform: 'instagram' },
]

export const CATEGORIES = [
  { value: 'all', label: 'Todas las Piezas' },
  { value: 'anillos', label: 'Anillos' },
  { value: 'collares', label: 'Collares' },
  { value: 'pulseras', label: 'Pulseras' },
  { value: 'aretes', label: 'Aretes' },
  { value: 'dijes', label: 'Dijes' },
  { value: 'sets', label: 'Sets' },
]
