import { type Product } from '@/lib/store'

const SILVER_JEWELRY_IMAGES = [
  'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1617038220319-276d3cfab638?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1515562141589-67f0d569b6f5?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop',
]

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-1',
    name: 'Celestial Moon Ring',
    description: 'Handcrafted 925 silver ring with crescent moon motif and cubic zirconia accent',
    price: 89.99,
    category: 'rings',
    sku: 'RG-001',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[0]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    name: 'Whisper Chain Necklace',
    description: 'Delicate silver chain necklace with minimalist pendant, perfect for layering',
    price: 129.99,
    category: 'necklaces',
    sku: 'NK-002',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[1]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    name: 'Ethereal Cuff Bracelet',
    description: 'Open-end cuff bracelet in polished 925 silver with organic flowing design',
    price: 149.99,
    category: 'bracelets',
    sku: 'BR-003',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[2]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    name: 'Drop Crystal Earrings',
    description: 'Elegant drop earrings featuring 925 silver setting with clear crystal drops',
    price: 69.99,
    category: 'earrings',
    sku: 'ER-004',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[3]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-5',
    name: 'Infinity Wrap Ring',
    description: 'Symbolic infinity design in oxidized silver with polished highlights',
    price: 79.99,
    category: 'rings',
    sku: 'RG-005',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[4]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    name: 'Riviera Choker',
    description: 'Statement choker in 925 silver with interlocking geometric elements',
    price: 199.99,
    category: 'necklaces',
    sku: 'NK-006',
    isFeatured: true,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[5]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-7',
    name: 'Wave Bangle Set',
    description: 'Set of 3 stacking bangles with wave-inspired texture in brushed silver',
    price: 119.99,
    category: 'bracelets',
    sku: 'BR-007',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[6]],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo-8',
    name: 'Pearl Stud Earrings',
    description: 'Classic pearl studs on 925 silver posts with secure butterfly backs',
    price: 59.99,
    category: 'earrings',
    sku: 'ER-008',
    isFeatured: false,
    isActive: true,
    media: [SILVER_JEWELRY_IMAGES[7]],
    createdAt: new Date().toISOString(),
  },
]

export const DEMO_HASHTAGS = [
  { id: 'ht-1', name: 'Silver Essentials', hashtags: ['#925Silver', '#SilverJewelry', '#SterlingSilver', '#SilverLove', '#PureSilver', '#SilverDesign', '#SilverCraft', '#JewelryAddict'], category: 'general', usageCount: 24 },
  { id: 'ht-2', name: 'Luxury Vibes', hashtags: ['#LuxuryJewelry', '#FineJewelry', '#ElegantStyle', '#TimelessBeauty', '#JewelryLovers', '#LuxuryLife', '#ChicJewelry', '#ClassyStyle'], category: 'luxury', usageCount: 18 },
  { id: 'ht-3', name: 'Ring Collection', hashtags: ['#SilverRing', '#RingGame', '#RingCollection', '#PromiseRing', '#StatementRing', '#MinimalRing', '#RingStack', '#RingStyle'], category: 'rings', usageCount: 31 },
  { id: 'ht-4', name: 'Trending Now', hashtags: ['#JewelryTrends', '#Jewelry2024', '#TrendingNow', '#MustHave', '#StyleInspo', '#OOTD', '#JewelryGram', '#InstaJewelry'], category: 'trending', usageCount: 15 },
]

export const DEMO_ANALYTICS = [
  { date: '2026-05-01', likes: 245, comments: 32, shares: 18, reach: 4200, platform: 'instagram' },
  { date: '2026-05-02', likes: 312, comments: 45, shares: 22, reach: 5100, platform: 'instagram' },
  { date: '2026-05-03', likes: 189, comments: 21, shares: 14, reach: 3200, platform: 'facebook' },
  { date: '2026-05-04', likes: 421, comments: 56, shares: 35, reach: 6800, platform: 'instagram' },
  { date: '2026-05-05', likes: 278, comments: 38, shares: 19, reach: 4500, platform: 'facebook' },
  { date: '2026-05-06', likes: 356, comments: 42, shares: 28, reach: 5600, platform: 'instagram' },
  { date: '2026-05-07', likes: 198, comments: 25, shares: 16, reach: 3400, platform: 'facebook' },
  { date: '2026-05-08', likes: 489, comments: 67, shares: 42, reach: 7200, platform: 'instagram' },
  { date: '2026-05-09', likes: 334, comments: 48, shares: 31, reach: 5400, platform: 'facebook' },
  { date: '2026-05-10', likes: 412, comments: 55, shares: 38, reach: 6500, platform: 'instagram' },
  { date: '2026-05-11', likes: 267, comments: 34, shares: 21, reach: 4300, platform: 'facebook' },
  { date: '2026-05-12', likes: 523, comments: 72, shares: 45, reach: 7800, platform: 'instagram' },
  { date: '2026-05-13', likes: 345, comments: 41, shares: 27, reach: 5100, platform: 'facebook' },
  { date: '2026-05-14', likes: 478, comments: 63, shares: 39, reach: 7000, platform: 'instagram' },
]

export const CATEGORIES = [
  { value: 'all', label: 'All Pieces' },
  { value: 'rings', label: 'Rings' },
  { value: 'necklaces', label: 'Necklaces' },
  { value: 'bracelets', label: 'Bracelets' },
  { value: 'earrings', label: 'Earrings' },
  { value: 'pendants', label: 'Pendants' },
  { value: 'sets', label: 'Sets' },
]
